# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tokenz < Formula
  desc "Store tokens in Apple Keychain for easy access in Terminal"
  homepage "https://github.com/willswire/tokenz"
  version "0.0.1"
  license "MIT"
  depends_on :macos

  on_intel do
    url "https://github.com/willswire/tokenz/releases/download/v0.0.1/tokenz_v0.0.1_macOS_x86_64.tar.gz"
    sha256 "6dfcbdbb9180da644fcfe18e4a4292a92a6200ed94aec4f62f900eb61cffb3e5"

    def install
      bin.install "tokenz"
    end
  end
  on_arm do
    url "https://github.com/willswire/tokenz/releases/download/v0.0.1/tokenz_v0.0.1_macOS_arm64.tar.gz"
    sha256 "40b69f1d891d4368fec098b6669f0ca7e1e5f39463963bfa0e5066698912db40"

    def install
      bin.install "tokenz"
    end
  end
end
