# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tokenz < Formula
  desc "Store tokens in Apple Keychain for easy access in Terminal"
  homepage "https://github.com/willswire/tokenz"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/willswire/tokenz/releases/download/v0.1.0/tokenz_v0.1.0_macOS_x86_64.tar.gz"
    sha256 "3ea65b628408530ce27770c84dd490c5a82552f0817ca746019a0d5b9fb22d0f"

    def install
      bin.install "tokenz"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/willswire/tokenz/releases/download/v0.1.0/tokenz_v0.1.0_macOS_arm64.tar.gz"
    sha256 "dffa938bf47c1e8cd2819e89ca3495a6156b2801b0a48e09dec7dd102668a959"

    def install
      bin.install "tokenz"
    end
  end
end
