# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tokenz < Formula
  desc "Store tokens in Apple Keychain for easy access in Terminal"
  homepage "https://github.com/willswire/tokenz"
  version "0.0.2"
  license "MIT"
  depends_on :macos

  on_intel do
    url "https://github.com/willswire/tokenz/releases/download/v0.0.2/tokenz_v0.0.2_macOS_x86_64.tar.gz"
    sha256 "cb3ccc3a3ed8988607c4118ca265f775a5d6a9c30a60923b0542642b8e1605de"

    def install
      bin.install "tokenz"
    end
  end
  on_arm do
    url "https://github.com/willswire/tokenz/releases/download/v0.0.2/tokenz_v0.0.2_macOS_arm64.tar.gz"
    sha256 "d87f0cda02d5d6254d93d8e5a962656fb6ed6e33ca585667374b2ce0429ebbe7"

    def install
      bin.install "tokenz"
    end
  end
end
